name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: 'Log into registry'
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags:  ${{ secrets.REGISTRY_LOGIN_SERVER }}/telegram-aircraft-bot/frontend:${{ github.sha }}